[package]
name = "cargo-pants"
version = "0.1.0"
authors = ["Glenn Mohre <glenn.mohre@gmail.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/gmohre/cargo-pants"

[dependencies]
futures = "0.1.0"
hyper = "0.11.25"
hyper-tls = "0.1.3"
prettytable-rs = "0.6.7"
serde = "1.0.42"
serde_derive = "1.0.42"
serde_json = "1.0.16"
tokio-core = "0.1.17"
url = "1.7.0"
