version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/rust:1.44.1'
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys: cargo-pants-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - save_cache:
          key: cargo-pants-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
          paths:
            - "~/.cargo"
            - "./target"
      - run:
          name: Run all tests
          command: cargo test --all
      - run: cargo install cargo-pants --force
      - run: cargo pants
